//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoEstacionamientos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CajaDiaria
    {
        public int idcaja { get; set; }
        public int idcliente { get; set; }
        public int idusuario { get; set; }
        public System.DateTime fecha { get; set; }
        public decimal importe { get; set; }
        public Nullable<decimal> faltante { get; set; }
        public string observacion { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
