//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoEstacionamientos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculos
    {
        public int idvehiculo { get; set; }
        public int idcliente { get; set; }
        public int idusuario { get; set; }
        public int idtipo { get; set; }
        public int idtarifa { get; set; }
        public System.DateTime ingreso { get; set; }
        public Nullable<System.DateTime> salida { get; set; }
        public string pagado { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Tarifas Tarifas { get; set; }
        public virtual TiposVehiculo TiposVehiculo { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
